name:                aoc2019
version:             0.1.0.0
github:              "saep/aoc2019"
license:             PublicDomain
author:              "Sebastian Witte"
maintainer:          "woozletoff@gmail.com"
copyright:           "2019 Sebastian Witte"

description:         Advent of Code solutions 2019

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- NoImplicitPrelude
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies

dependencies:
- base >= 4.7 && < 5
- rio
- pretty-simple
- megaparsec
- polysemy
- polysemy-plugin
- primitive
- streamly
- vector
# actually just testing 
- hspec
- QuickCheck

library:
  source-dirs: src
  ghc-options:
  - -funbox-strict-fields
  - -Wall
  - -fno-warn-unused-do-bind
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively

tests:
  hspec:
    main: Spec.hs
    source-dirs: tests
    dependencies:
    - QuickCheck >=2
    - hspec
    - aoc2019
